import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Image from "next/image"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Apex Pioneer Group',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="bg-opacity-80 bg-gray-300 flex flex-row text-black items-center pr-20 pl-10">
          <div className="m-2 pr-2 sm:border-r border-gray-600">
            <Image alt="Apex Logo" width={50} height={50} src="/Screenshot_2023-11-11_at_11.51.06_AM-removebg-preview.png" />
          </div>

          <h4 className="hidden sm:block">
            <b>
              <a href="#">
                Apex Pioneer Group
              </a>
            </b>
          </h4>

          <div className="flex-1"></div>

          <ul className="list-none flex flex-row gap-4">
            <li>
              <a href="#">
                About
              </a>
            </li>

            <li>
              <a href="#">
                Services
              </a>
            </li>
            
            <li>
              <a href="#">
                Contact
              </a>
            </li>
          </ul>
        </header>

        {children}
      </body>
    </html>
  )
}
